name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: occorps
      JWT_SECRET_KEY: occorps
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:3366@127.0.0.1/review_test  # Kết nối MySQL

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 3366
          MYSQL_DATABASE: review_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL to be ready
      run: |
        for i in $(seq 1 30); do
          if mysqladmin ping -h "127.0.0.1" --silent; then
            echo "MySQL is ready!"
            break
          else
            echo "Waiting for MySQL to be ready..."
            sleep 5
          fi
        done

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Tùy chọn để giảm chi tiết log
