name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose

    - name: Build and run Docker containers
      run: |
        docker-compose up -d

    - name: Wait for services to be ready
      run: |
        sleep 10  # Đảm bảo các dịch vụ có thời gian để khởi động. Điều này có thể được thay bằng lệnh đợi thực tế hoặc healthcheck.

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Tear down Docker containers
      run: |
        docker-compose down
